### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by prosa100** [bagnalla/holyc_mal#1]
What is special about holyc? Besides it runs on TempleOS?

**Comment by ghost** [comment]
This is not exactly an issue relating to the project, but this page in the templeos documentation might help: https://templeos.sheikhs.space/Wb/Doc/HolyC.html

**Comment by bagnalla** [comment]
The documentation is a decent overview of the language, and [this](http://www.codersnotes.com/notes/a-constructive-look-at-templeos/) is an interesting writeup about TempleOS and HolyC.

In short: the author of HolyC (Terry Davis) describes it as being more than C and less than C++. It is mostly based on C, but takes a few features from C++ such as default arguments and exception handling. HolyC has "classes" as well, but they are mostly just C structs with some additional metadata features as far as I can tell.

Perhaps the most interesting thing about HolyC is that it's primarily a JIT-compiled language, and the TempleOS command line shell works by simply feeding your input line-by-line into the HolyC JIT compiler.
